version: '3'

services:

  backend-book:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: yavibook
    ports:
      - "8082:3200"
    env_file:
      - ../src/.env
    networks:
      - my-network
networks:
  my-network:
    driver: bridge