version: '3'

services:

  backend-Book:
    build:
      context: .
      dockerfile: dockerfile
    container_name: yavibook
    ports:
      -"8082:3200"
    env_file:
      - ./src/.env
    networks:
      - my-network
networks:
  my-network:
    driver: bridge